// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:quicksplit/features/assign/domain/models/item_assignment.dart';
import 'package:quicksplit/features/assign/domain/models/person_share.dart';
import 'package:quicksplit/features/assign/domain/models/split_session.dart';
import 'package:quicksplit/features/groups/domain/models/group.dart';
import 'package:quicksplit/features/groups/domain/models/person.dart';
import 'package:quicksplit/features/ocr/domain/models/receipt.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(GroupAdapter());
    registerAdapter(ItemAssignmentAdapter());
    registerAdapter(PersonAdapter());
    registerAdapter(PersonShareAdapter());
    registerAdapter(ReceiptAdapter());
    registerAdapter(ReceiptItemAdapter());
    registerAdapter(SplitSessionAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(GroupAdapter());
    registerAdapter(ItemAssignmentAdapter());
    registerAdapter(PersonAdapter());
    registerAdapter(PersonShareAdapter());
    registerAdapter(ReceiptAdapter());
    registerAdapter(ReceiptItemAdapter());
    registerAdapter(SplitSessionAdapter());
  }
}
